### ISSUE TITLE
fatal error: shakey_object_recognition/PushableObject.h: No such file or directory

### ISSUE THREAD

**Issue by HelenHarman** [speckdavid/shakey2016#1]
I attempted to run catkin_make but received the error: 
> fatal error: shakey_object_recognition/PushableObject.h: No such file or directory

Is the PushableObject.h file available?

Kind regards,
Helen

**Comment by speckdavid** [comment]
Thanks for the remark. A dependency was missing such that PushableObject.h was built after a file which required it. I added the dependency. I am able now to build the project without an error on my system.

If the same error or a similar one occurs, you can try to run catkin_make twice. Please let me know if the error still occurs on your system.

Kind regards,
David

**Comment by HelenHarman** [comment]
Great thank you. 
I ran in to a few issues due to using the latest version of ROS (and other libraries), but catkin_make now runs successfully. 

Kind regards,
Helen
