### ISSUE TITLE
ResourceNotFound: manipulation_objects

### ISSUE THREAD

**Issue by HelenHarman** [speckdavid/shakey2016#2]
When attempting to launch shakey_spawn_objects I get the following error message:
> ResourceNotFound: manipulation_objects

Is the manipulation_objects package available? 

Kind regards,
Helen

**Comment by speckdavid** [comment]
I added the missing package. Sorry for the inconvenience. I hope everything is now working. If you have any further problems or questions, please don't hesitate to contact me.

Kind regards,
David

**Comment by HelenHarman** [comment]
Thank you.
Helen
