### ISSUE TITLE
program freezes when attempting to execute drive-base action 

### ISSUE THREAD

**Issue by HelenHarman** [speckdavid/shakey2016#3]
Sorry to bother you again. 

The planner attempts to execute the action drive-base:
```
[ INFO] [1483452691.642152955, 114.083000000]: Created goal for ActionExecutorDriveBase as: target_pose: 
  header: 
    seq: 0
    stamp: 114.083000000
    frame_id: /map
  pose: 
    position: 
      x: -5.05378
      y: -1.08206
      z: 1.14807e-08
    orientation: 
      x: 0
      y: 0
      z: 0.212908
      w: 0.977072

[ INFO] [1483452691.644088357, 114.083000000]: Sending goal for action: drive-base.
```
However, the action is never completed. The drive-base action does not exist.
Should the action drive-base exist? 
(For now I can test this out by using move_base.)

Please correct me if my understanding of how this works is wrong.

Kind regards,
Helen

**Comment by speckdavid** [comment]
Hi,

a topic was wrong assigned. More precisely, I changed some topic names in the past. Here, the navigation stack was listening to the wrong topic (caused by renaming) and never received a goal position. Sorry for the inconvenience. I fixed the topic assignment now.

King regards,
David

**Comment by HelenHarman** [comment]
Hi David,

It is now up and running. 
Thank you.

Helen
